name: CI Weather Forecast

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# agar gitHub actions bisa melakukan push code balik ke repo
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        pip install mlflow pandas numpy scikit-learn matplotlib

    # menjalankan training
    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run . --env-manager=local

    # menyimpan artefak ke repository gitHub
    - name: Commit and Push MLflow Runs to Repo
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # menambahkan folder mlruns (hasil training) dan run_id.txt ke git
        git add MLProject/mlruns MLProject/run_id.txt
        
        # commit dan push
        git commit -m "Auto-commit: Update MLflow runs and artifacts" || echo "No changes to commit"
        git push

    # login ke docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # build docker image dan push
    - name: Build and Push Docker Image with MLflow
      run: |
        cd MLProject
        
        # membaca Run ID dari file yang dihasilkan modelling.py
        RUN_ID=$(cat run_id.txt)
        echo "Building Docker for Run ID: $RUN_ID"
        
        # build Docker Image menggunakan fungsi bawaan MLflow
        # format model utl lokal: runs:/<run_id>/model
        mlflow models build-docker \
          -m "runs:/$RUN_ID/model" \
          -n "${{ secrets.DOCKER_USERNAME }}/weather-forecast:latest" \
          --enable-mlserver
        
        # push ke docker hub
        docker push "${{ secrets.DOCKER_USERNAME }}/weather-forecast:latest"