name: CI Weather Forecast

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # run actions/checkout@v3
    - name: Run actions/checkout@v3
      uses: actions/checkout@v3

    # set up python 3.12.7
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    # check env
    - name: Check Env
      run: |
        python --version
        pip --version

    # install dependencies
    - name: Install dependencies
      run: |
        pip install mlflow==2.19.0 pandas numpy scikit-learn matplotlib

    # run mlflow project
    - name: Run mlflow project
      run: |
        cd MLProject
        mlflow run . --env-manager=local --experiment-name "Weather Forecast CI"

    # get latest mlflow run_id
    - name: Get latest MLflow run_id
      run: |
        cd MLProject
        RUN_ID=$(cat run_id.txt)
        echo "Run ID Found: $RUN_ID"

    # install python dependencies 
    - name: Install Python dependencies
      run: |
        pip install pandas numpy scikit-learn matplotlib

    # 9. upload to gitHub
    - name: Upload to GitHub
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add MLProject/mlruns MLProject/run_id.txt
        git commit -m "Auto-commit: Update MLflow runs and artifacts" || echo "No changes to commit"
        git push

    # build docker model
    - name: Build Docker Model
      run: |
        cd MLProject
        RUN_ID=$(cat run_id.txt)
        mlflow models build-docker \
          -m "runs:/$RUN_ID/model" \
          -n "${{ secrets.DOCKER_USERNAME }}/weather-forecast:latest" \
          --enable-mlserver

    # log in to docker hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # tag docker image
    - name: Tag Docker Image
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/weather-forecast:latest ${{ secrets.DOCKER_USERNAME }}/weather-forecast:v1

    # push docker image
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/weather-forecast:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/weather-forecast:v1